test_task_tree_menu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tree.urls', namespace='tree')),
]

tree/urls.py
from django.urls import path
from . import views


app_name = 'tree'


urlpatterns = [
    path('list-menu/<int:id>', views.display_menu, name='display-menu'),
    path('list-menu/', views.list_menu, name='list-menu'),
]

tree/models.py
from django.db import models

# Create your models here.


class Menu(models.Model):
    name = models.CharField(max_length=120)
    url = models.CharField(max_length=255, blank=True, null=True)


class MenuItem(models.Model):
    menu = models.ForeignKey('Menu', on_delete=models.CASCADE, related_name="items")
    name = models.CharField(max_length=120)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name="children", blank=True, null=True)
    url = models.CharField(max_length=255, blank=True, null=True)

tree/views.py
from django.shortcuts import render, get_object_or_404
from .models import Menu

# Create your views here.


def display_menu(request, id):
    menu = get_object_or_404(Menu, pk=id)
    context = {
        'menu_name': menu.name
    }
    return render(request, 'tree/display.html', context=context)


def list_menu(request):
    menu_list = Menu.objects.all()
    return render(request, 'tree/list_menu.html', {'menu_list': menu_list})

tree/templates/tree/display.html
{% load menu_extras %}
{% draw_menu menu_name %}

tree/templates/tree/list_menu.html
{% for menu in menu_list %}
    <li>
        <a href="{% url 'tree:display-menu' menu.id %}">{{ menu.name }}</a>
    </li>
{% endfor %}

tree/templates/tree/menu_template.html
{% load menu_extras %}


<style>
    .menu a.active {
        background-color: lightblue;
    }
</style>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        // Add a click event listener to all menu items
        var menuItems = document.querySelectorAll('.menu a');
        menuItems.forEach(function (item) {
            item.addEventListener('click', function () {
                // Remove the 'active' class from all menu items
                menuItems.forEach(function (menuItem) {
                    menuItem.classList.remove('active');
                });

                // Add the 'active' class to the clicked menu item
                item.classList.add('active');
            });
        });
    });
</script>

<ul class="menu">
    {% for item in menu_items %}
        <li>
            <a href="javascript:void(0);" data-item-id="{{ item.id }}" class="menu-item">{{ item.name }}</a>
            {% if item.children.all %}
                {% draw_menu_recursive item %}
            {% endif %}
        </li>
    {% endfor %}
</ul>